name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jakoch/install-vulkan-sdk-action@v1
      with:
        vulkan_version: 1.4.313.0
        install_runtime: true
        cache: true
        stripdown: true
    - name: Install Mesa Vulkan driver
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-vulkan-drivers
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
